# Generated by Django 3.2 on 2022-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_questions_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='content',
            field=models.TextField(),
        ),
    ]
