# Generated by Django 3.2 on 2022-06-17 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_questions_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['created_on'], 'verbose_name_plural': 'Questions'},
        ),
    ]
