# Generated by Django 3.2 on 2022-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_number', models.CharField(editable=False, max_length=32)),
                ('ad_payment_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
