# Generated by Django 3.2 on 2022-06-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
