# Generated by Django 3.2 on 2022-06-06 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loppises', '0002_alter_loppis_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loppis',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loppises.county'),
        ),
    ]
